### ISSUE TITLE
GNU Tools for ARM Embedded Processors

### ISSUE THREAD

**Issue by ladislas** [osx-cross/osx-cross#1]
Hi guys!

I just bought a Teensy 3.1 and after playing with it through the Arduino IDE, I wanted to test if [Sudar's Arduino-Makefile](https://github.com/sudar/Arduino-Makefile) and the [GNU ARM Toolchain](https://launchpad.net/gcc-arm-embedded) would play nice together.

Turns out you need Arduino IDE 1.0.6 + Teensyduino + some hacking to the `Makefile` to be able to use your own toolchain but it works pretty well.

I created a repo with the formula, you guys can take a look at it:  
https://github.com/ladislas/homebrew-arm

It's pretty simple as everything is already compiled and packaged. You just need to copy the directories to the right place and voila!

If it's okay with you, I'll add it to osx-cross :)

**Comment by leojrfs** [comment]
Hey!
Im sorry, i've been very busy lately...

It looks good!

Last time i've played with a micro controller it was a cortex-m0, i also thought of including cross-arm here.

Anyways, i see that your formula installs a precompiled compiler binary. We should also add the usual (compiled) formula and name yours : "compiler-bin" or any other naming policy, rules or wharever, homebrew has.

references:
- https://github.com/jsnyder/arm-eabi-toolchain
- https://launchpadlibrarian.net/209775843/How-to-build-toolchain.pdf (Page 7)

In the meantime, i think it is ok to add it here (since all we got for now is "unstable")

Lets see what the others say...

:smiley:

**Comment by ladislas** [comment]
> Anyways, i see that your formula installs a precompiled compiler binary. We should also add the usual (compiled) formula and name yours

@leojrfs, you're right, it would be good to allow people to build it from source. I tried it with the instructions you provided and it takes an awful lot of time and in the end did not even work... As I just wanted it to work, I used the precompiled binaries.

If you download their [sources](https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-src.tar.bz2) to compile them, you'll see they have build scripts available. I guess we could just "copy" what they do but I'm not and expert and it looked rather complicated. I also looked at jsnyder repo but the version of gcc he is using 4.8. A mix of the two could be the solution.

As for the naming rules, adding `bin` at the end is not a bad idea. What do you guys think?

**Comment by leojrfs** [comment]
@ladislas no one said anything, so push here and add '-bin' to the formula name.
I will soon start playing with ARM mcpus and will help you polish that formula :smile:

**Comment by ladislas** [comment]
Hi there!

Waking up this thread in regard of the recent update in the formula.

We recently had issues regarding conflicts with the avr-gcc and gcc itself, and we fixed those issues.

In the process, I found out that there is an official "arm-gcc" formula provided by [Arm Mbed](https://github.com/ARMmbed) themselves -- https://github.com/ARMmbed/homebrew-formulae

I'm wondering if we should keep our version or just let them handle it. After all, they are the one providing the compiled binaries, they should also be in charge of maintaining their own formulae.

For us the formula is not a burden at all, it's seldom updated and contains 14 lines of code. It's more to help users and try not to confuse them with two formulae that are almost similar.

What do you guys think?

**Comment by leojrfs** [comment]
Hey!
I think so, maybe we should redirect this repo?
