### ISSUE TITLE
Toolchains for ARM Cortex-A

### ISSUE THREAD

**Issue by btwael** [osx-cross/osx-cross#2]
I would like to see toolchains for ARM Cortex-A, the available `brew` in the wild are not complete (generally missing `g++`)?

Thank you

**Comment by ladislas** [comment]
Hi @btwael -- sorry I missed your post...

The toolchain is available here: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads

But as far as I can see, there does not seem to be any macOS toolchains :\

I have no experience what so ever with Cortex A but if you do and want to work on a formula, we can create a new repo for that.

Let me know.

**Comment by ladislas** [comment]
Closing as there hasn't been any news. Feel free to reopen.
